import os
import re
import logging
import javalang
from javalang.parser import JavaSyntaxError
from javalang.tree import MethodDeclaration

GENERATED_TEST_METHOD_NAME = "generatedTestCaseByLLM"

def parse_generated_test_case(llm_response) -> str:
    # Regular expression to match the full method by name
    pattern = r"```java(.*)```"
    matches = re.findall(pattern, llm_response, re.DOTALL)
    # Ensure only one match is found
    if len(matches) == 1:
        # Construct the full method definition
        method_code = str(matches[0].strip())
        if method_code.startswith("@Test"):
            method_code = method_code.replace("@Test", "", 1).strip()
        # Parse java code to validate syntax
        wrapped_code = f"""
        public class DummyClass {{
            {method_code}
        }}
        """
        tree = javalang.parse.parse(wrapped_code)
        for path, node in tree.filter(MethodDeclaration):
            # Check if the node matches the method name
            if node.name == GENERATED_TEST_METHOD_NAME:
                break
            else:
                logging.error("Fail to parse the generated test case due to incorrect method name!")
                return None
        logging.info("Test Case Generated by LLM\n" + method_code)
        return method_code
    elif len(matches) == 0:
        logging.warning("Method not found.")
    else:
        logging.warning("Error: Multiple matches found for the method.")

def add_generated_test_case(trigger_test_path, test_method_name, generated_test_case):
    """
    Replaces the original trigger test case with the one generated by LLM.
    """
    # Read the original file content
    try:
        with open(trigger_test_path, 'r') as file:
            content = file.read()
        with open(trigger_test_path, 'r') as file:
            lines = file.readlines()

        original_tree = javalang.parse.parse(content)
        original_test_line = None
        # Traverse the tree to find the target method
        for path, node in original_tree.filter(MethodDeclaration):
            # Check if the node matches the method name
            if node.name == test_method_name:
                original_test_line = node.position.line
                break
        if original_test_line is None:
            logging.warning("Fail to find the original test case!")
            return
        
        target_line = original_test_line - 1
        if "@Test" in lines[target_line - 1]:
            target_line -= 1
            generated_test_case = "@Test\n" + generated_test_case
        
        # Add generated test case to the test suite
        for newline in reversed(generated_test_case.split('\n')):
            lines.insert(target_line, newline + '\n')

        # Validate Java syntax of augmented test suite
        javalang.parse.parse("".join(lines))

        with open(trigger_test_path, 'w') as file:
            file.writelines(lines)
        logging.info(f"Successfully added the trigger test case in the file {trigger_test_path}")
        return True
        
    except FileNotFoundError:
        logging.error(f"Error: File not found at {trigger_test_path}")
    except JavaSyntaxError as e:
        logging.error(f"The updated test suite is NOT syntactically correct! {e}")
    except Exception as e:
        logging.error(e)

def get_test_case_filenames(experiment_path):
    return filter(lambda filename : "testcase.txt" in filename, os.listdir(experiment_path))

def get_generated_test_name(trigger_test_name):
    # Regex pattern to match everything after '::'
    pattern = r'::.*'
    
    # Replace everything after '::' with the new string
    result = re.sub(pattern, f'::{GENERATED_TEST_METHOD_NAME}', trigger_test_name)
    return result
